// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Arena.h"
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "NetRifle.generated.h"

class ANetCharacter;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FNetAmmoChangedSignature, int32, CurrentAmmo, int32, MagazineSize);

/**
 * Minimal hitscan rifle for the network gameplay variant.
 */
UCLASS(Blueprintable)
class ARENA_API ANetRifle : public AActor
{
	GENERATED_BODY()

public:
	ANetRifle();

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	/** Start firing the rifle on Server. */
	void StartFiringOnServer();

	/** Stop firing the rifle on Server. */
	void StopFiringOnServer();

	/** Returns the last line trace result produced by this rifle. */
	UFUNCTION(BlueprintPure, Category="Weapon")
	FHitResult GetLastHitResult() const { return LastHitResult; }

	/** Returns true if the last shot hit a blocking target. */
	UFUNCTION(BlueprintPure, Category="Weapon")
	bool HasValidHitResult() const { return LastHitResult.bBlockingHit; }

	UFUNCTION(BlueprintPure, Category="Weapon|Ammo")
	int32 GetCurrentAmmo() const { return CurrentAmmo; }

	UFUNCTION(BlueprintPure, Category="Weapon|Ammo")
	int32 GetMagazineSize() const { return MagazineSize; }

	UPROPERTY(BlueprintAssignable, Category="Weapon|Ammo")
	FNetAmmoChangedSignature OnAmmoChanged;

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	/** Fire one hitscan shot if cooldown allows it on Server */
	void FireOnServer();

	/** Called when the fire cooldown expires. */
	void FireCooldownExpired();

	/** Performs the camera-centered rifle trace. */
	bool TraceFromCamera(FHitResult& OutHitResult) const;

	/** Performs one authoritative shot on the server. */
	void FireAuthoritativeShot();

protected:
	/** Maximum trace distance from the camera center. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Weapon", meta=(ClampMin=0, Units="cm"))
	float TraceDistance = 10000.0f;

	/** Minimum time between shots. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Weapon", meta=(ClampMin=0, Units="s"))
	float FireCooldown = 0.2f;

	/** Trace channel used by the rifle. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Weapon")
	TEnumAsByte<ECollisionChannel> TraceChannel = ECC_WeaponTrace;

	/** Damage applied to the actor hit by the rifle trace. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Weapon", meta=(ClampMin=0))
	float Damage = 20.0f;

	UPROPERTY(EditAnywhere, Replicated, BlueprintReadOnly, Category="Weapon|Ammo", meta=(ClampMin=1))
	int32 MagazineSize = 30;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Weapon|Ammo")
	bool bConsumeAmmo = false;

	UPROPERTY(VisibleInstanceOnly, ReplicatedUsing=OnRep_CurrentAmmo, BlueprintReadOnly, Category="Weapon|Ammo")
	int32 CurrentAmmo = 30;

	/** Lifetime for the server-authoritative debug trace line. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Debug", meta=(ClampMin=0, Units="s"))
	float DebugTraceDuration = 0.05f;

	/** Last hit result generated by the rifle. */
	UPROPERTY(VisibleInstanceOnly, Replicated, BlueprintReadOnly, Category="Weapon")
	FHitResult LastHitResult;

	/** Character that owns this rifle. */
	UPROPERTY()
	TObjectPtr<ANetCharacter> OwningCharacter;

	bool bCanFire = true;
	bool bWantsToFire = false;

	FTimerHandle FireCooldownTimer;

private:
	UFUNCTION()
	void OnRep_CurrentAmmo();

	void BroadcastAmmoChanged();
};
